### ISSUE TITLE
라이센스가 GPL이네요.

### ISSUE THREAD

**Issue by kybin** [lazypic/koi#2]
생각보다 혁씨 하드하네요!

**Comment by khw7096** [comment]
라이센스 정책을 이야기 해주니... 그 라이센스를 선택!! 하드함!!ㅋㅋ

**Comment by kohyuk91** [comment]
bootstrap 같은 css framework 사용하면 라이센스 바꿔야 하나욥?

**Comment by kybin** [comment]
그렇지는 않을것 같은데.. 잘 모르겠어요. 저는 라이센스 전문가가 아니라서 ㅎㅎㅎ

**Comment by kybin** [comment]
굿 나잇!

**Comment by khw7096** [comment]
보통은 자신이 가져다가 사용하는 라이브러리가 있다면 그 라이브러리의 라이센스를 맞추는것도 좋아요~!
