### ISSUE TITLE
Handsontable 테스트

### ISSUE THREAD

**Issue by kohyuk91** [lazypic/koi#6]
https://handsontable.com/

나중에 DB랑 연동할때
HTML 테이블 사용하는게 손이 많이갈지
Web Excel을 사용하는게 손이 많이갈지...

테스트 테스트

**Comment by kohyuk91** [comment]
Handsontable 적용!

**Comment by khw7096** [comment]
so good. 

현재는 논커머셜 라이센스예용?

**Comment by sehwanjo10** [comment]
레고레고~!

**Comment by kohyuk91** [comment]
> so good.
> 
> 현재는 논커머셜 라이센스예용?

Handsontable이 논커머셜 라이센스라 일단 그렇게 셋팅해놨어욥 ㅋ
