### ISSUE TITLE
절대 경로 파싱

### ISSUE THREAD

**Issue by kohyuk91** [lazypic/koi#7]
```      
var files = ["data/show/test_project.csv", "/storage/koi/data/show/test_project2.csv"];

for (var f = 0; f < files.length; f++) {
    var offset = 0;
    Papa.parse(files[f], {
        download: true,
        header: false,
        skipEmptyLines: true,
        complete: function (results) {
```

파일 여러개를 파싱하는 for문 일부분입니다,
상대경로로 작성한 test_project.csv 파일을 잘 들어오는데
절대경로로 작성한 test_project2.csv 파일은 읽지 않고 스킵해버리네요 ㅜ

**Comment by kybin** [comment]
정말 상대경로 절대경로 문제인지 확인하기위해 한번 같은 파일을 불러보세요

**Comment by kohyuk91** [comment]
> 정말 상대경로 절대경로 문제인지 확인하기위해 한번 같은 파일을 불러보세요

아 다시 보니까 KOI Repository 안에 있는 파일은 인식하는데,
KOI Repository 밖에 있는 csv 파일을 스킵하는것 같네용

**Comment by kybin** [comment]
~~그냥 파일이나 파일명이아니라 readable stream을 쓰라고 하네요.~~

~~https://stackoverflow.com/a/52350312/1932530~~

프론트엔드 툴킷이라 제가 생각했던 것과는 다르겠네요. 웹으로 파일을 받아 읽는 방식으로 되어있나봐요.

각각의 링크가 가리키는 페이지가 실제로 존재해야 할 것 같아요.

https://lazypic.github.io/koi/data/show/test_project.csv
https://lazypic.github.io/koi/storage/koi/data/show/test_project2.csv

**Comment by khw7096** [comment]
오~ 저도 지식을 그냥 얻어가네요.  +2
